spring.application.name=session09
spring.datasource.url=jdbc:postgresql://localhost:5432/session09
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

cloundinary.cloud_name=dq6f7y2tu
cloundinary.api_key=246414255899469
cloundinary.api_secret=GIO4Mej4crWrNZUNAd_erxt-v2g